# Generated by Django 3.2.9 on 2021-11-12 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(max_length=64)),
                ('date_in', models.DateField()),
                ('date_out', models.DateField()),
                ('registration_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.aircraft')),
            ],
        ),
    ]
