# Generated by Django 3.2.9 on 2021-11-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=8)),
                ('description', models.TextField(max_length=275)),
                ('model_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.acmodel')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
            ],
        ),
        migrations.RemoveField(
            model_name='aircraft',
            name='model',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date_in',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date_out',
        ),
        migrations.CreateModel(
            name='WorkContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.task')),
                ('workorder_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.workorder')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('aircraft_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.aircraft')),
            ],
        ),
        migrations.AddField(
            model_name='aircraft',
            name='model_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.acmodel'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.customer'),
        ),
    ]
