# Generated by Django 3.2.9 on 2021-11-28 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.acmodel'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.task'),
        ),
    ]
