# Generated by Django 3.2.9 on 2021-12-01 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20211128_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='model_id',
            new_name='model',
        ),
    ]
